### ISSUE TITLE
error

### ISSUE THREAD

**Issue by valvi1** [FUst1ke/fusti_gangmap#2]
good I get this error in console
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/7c695862-3a93-4cad-a8c8-35f75dcf3677)

**Comment by FUst1ke** [comment]
Hello, how can you reproduce this problem? Make sure you are using at least es_extended version 1.9.4, this is where xPlayer.set and getMeta were included as a new feature. Also try to update your artifact.

**Comment by valvi1** [comment]
> Hello, how can you reproduce this problem? Make sure you are using at least es_extended version 1.9.4, this is where xPlayer.set and getMeta were included as a new feature. Also try to update your artifact.

esx onesic legacy
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/2ced9687-1f51-4eb8-8ad3-4710332cd93a)
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/671bb54f-8b8e-46fb-92bb-c6953ea555b9)

**Comment by FUst1ke** [comment]
how do you reproduce it?

**Comment by valvi1** [comment]
> how do you reproduce it?

![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/3ee2ce08-6714-4cbe-843f-08423e312e74)
when I die
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/9056b5ce-7969-45f4-859e-2f2c8b55279d)

**Comment by FUst1ke** [comment]
have you touched any code?

**Comment by valvi1** [comment]
> have you touched any code?

![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/adc3cea6-ea5a-4e37-96a1-12246fe70867)
I put it again but it still comes out even though I moved the sql but it has nothing to do with the scrip.

[essentialmode1.txt](https://github.com/FUst1ke/fusti_gangmap/files/13925172/essentialmode1.txt)

**Comment by FUst1ke** [comment]
this isnt contains my sql..

**Comment by FUst1ke** [comment]
if you update your es_extended you should update the whole core, which contains your database. you have no metadata column in the user, so the xPlayer set and get Meta wont work. That is why I said to upgrade your core.

**Comment by valvi1** [comment]
> if you update your es_extended you should update the whole core, which contains your database. you have no metadata column in the user, so the xPlayer set and get Meta wont work. That is why I said to upgrade your core.

this metadata ?
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/b0397214-2629-4556-8b64-43c30c05c432)

**Comment by FUst1ke** [comment]
yes

**Comment by valvi1** [comment]
> yes

.... already had it

**Comment by FUst1ke** [comment]
![image](https://github.com/FUst1ke/fusti_gangmap/assets/118769783/c53b7726-ea67-4310-8a07-2d3d2d9440a9)
then why are you sending me wrong sql..

**Comment by valvi1** [comment]
> ![image](https://private-user-images.githubusercontent.com/118769783/296397825-c53b7726-ea67-4310-8a07-2d3d2d9440a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDcyMjIsIm5iZiI6MTcwNTEwNjkyMiwicGF0aCI6Ii8xMTg3Njk3ODMvMjk2Mzk3ODI1LWM1M2I3NzI2LWVhNjctNDMxMC04YTA3LTJkM2QyZDk0NDBhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwMDQ4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzZkZWY1YzdlMzUwZTY1MzI3MWI3OGQwMmNmM2QxNTUwODYxNDYyMzA2ZGRjMWQwYmFiZTU2Yzg1YjdkYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RSEuwlpj2mthWARE_5RYSIu6uQRgpbM2zjwTCk3PIgA) then why are you sending me wrong sql..

I sent you the one that I had uploaded from another script that modified the sql that if it had something to do with why that comes out.
sorry I use translator

**Comment by FUst1ke** [comment]
dont send me some outdated sql, use the fresh core with the fresh es_extended and with the fresh database, it will work. I won't give support to modified code due to its not my responsibility if you can code or not.

**Comment by valvi1** [comment]
> dont send me some outdated sql, use the fresh core with the fresh es_extended and with the fresh database, it will work. I won't give support to modified code due to its not my responsibility if you can code or not.

I'm sorry but as you asked what modifications I had done, well the thing is that I restored my database, deleted my character and unfortunately I still get the message in the console (the scrip works only because of the message that comes out).

now it looks like this  
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/b2376bce-99ff-4b56-afec-035924be2f1e)
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/6ffa5869-3bca-446e-bbb7-b94bc95758b1)

**Comment by FUst1ke** [comment]
you have an error in the server/shared. Why are you sending me pictures of the client file?

**Comment by valvi1** [comment]
jajaj sorry 
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/dd3609bb-c7b7-42ef-9bcb-c0d96f448311)

is it because my server has a double job?
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/ae9ebc3e-94be-47c0-b1e6-08e19cdcfd9f)
![image](https://github.com/FUst1ke/fusti_gangmap/assets/136049869/0ecec913-4d27-451c-90e7-59ed94830983)

**Comment by FUst1ke** [comment]
this script does not support double job. also not supporting modified core.
